# Generated by Django 3.1.1 on 2020-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200910_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
